# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 5eaaaacfaa09deb298f4d70f293f273be92a3c2cb59e6b7673ab5cd0d17fda717f033fc468993d82313f8fa60891c00128a02b916ea0a88a4ea1d4990cec3fd5

test:
  secret_key_base: c68686387b28abfd39e182c6852a358826e1052c56c6a8645167a4d319b05714751f361322581b9588092aff4059ccc1e97fb047c9a3bc657c4f704356f22c78

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
